### ISSUE TITLE
 which network structures the project supports.

### ISSUE THREAD

**Issue by guods** [ivder/TensorRT-Image-Classification#1]
Thank you for your code. I want to know  which network structures the project supports，could you tell me that you use network structures ?

**Comment by ivder** [comment]
@guods do you mean the CNN model? I've never tested other network other than GoogleNet or Inception V1

**Comment by guods** [comment]
Have you tested GoogleNet and Inception V1? Could you share your models?

**Comment by ivder** [comment]
@guods Yes I tried Googlenet using my own model. You can find the example of using pre-trained googlenet caffe model like : https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet and https://github.com/BVLC/caffe/blob/master/data/ilsvrc12/get_ilsvrc_aux.sh

Or you can train your custom model using caffe framework or NVIDIA DIGITS with caffe framework, it will produce these files which are needed by this program (filename could be different): 

- deploy.prototxt
- network.caffemodel
- mean.binaryproto
- labels.txt

**Comment by guods** [comment]
Thank you for your reply! I would like to try it.
